[project]
name = "grafana-schema"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
dynamic = ["version"]

[tool.hatch.version]
source = "vcs"

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"
